export const fruits = [
    "Apple",
    "Banana",
    "Strawberry",
    "Blueberry",
    "Mango",
    "Pomengrante",
    "Apricot",
    "Kiwi",
    "Pineapple",
    "Orange",
    "Passion Fruit",
    "Dragonfruit",
    "Grapefruit",
    "Watermelon",
    "Melon",
    "Grape",
    "Lemon",
    "Lime",
    "Papaya",
    "Pear",
    "Cherry",
    "Avocado",
    "Starfruit",
    "Guava",
    "Blackberry",
    "Gooseberry",
    "Lingonberry",
    "Pitaya",
    "Goji Berry",
    "Cashew Fruit",
    "Soursop",
    "Acai",
    "Lychee",
    "Fig",
    "Cranberry"
]

export const vegetables = [
    "Broccoli",
    "Cauliflower",
    "Onion",
    "Green Onion",
    "Corn",
    "Squash",
    "Leek",
    "Lettuce",
    "Argula",
    "Kale",
    "Parsley",
    "Mint"
    "Bean sprouts",
    "Radish",
    "Turnip",
    "Parsnip",
    "Mushroom",
    "Watercress",
    "Potato",
    "Sweet Potato",
    "Rhubarb",
    "Bell pepper",
    "Peas",
    "Ginger",
    "Cilantro",
    "Fennel",
    "Tomato",
    "Garlic",
    "Green Bean",
    "Eggplant",
    "Zucchini",
    "Carrot",
    "Celery",
]

export const meats = [
    "Beef",
    "Bison",
    "Pork",
    "Duck",
    "Lamb",
    "Goat",
    "Veal",
    "Turkey",
    "Chicken",
]

export const seafood = [
    "Shrimp",
    "Fish",
    "Oyster",
    "Mussel",
    "Clam",
    "Crawfish",
    "Prawn",
    "Scallop",
    "Crabs"
]

export const grains = [
    "Sandwich bread",
    "Sourdough bread",
    "Rye bread",
    "Quiona",
    "Cracked wheat",
    "Brown Rice",
    "White Rice",
    "Oats"
]